#!/bin/sh
# Camagru php container entrypoint.
# 1. Generate /etc/msmtprc from env vars (msmtp mail driver).
# 2. Run the DB setup (waits for the DB, creates missing tables).
# 3. Exec php-fpm.
#
# Native logging: msmtp gets no logfile/syslog directive, so its errors go to
# stderr; the application logs through PHP's error log. Both reach the
# container console.

set -eu

mkdir -p /var/www/camagru/uploads
# The php-fpm workers run as www-data: they must be able to write the uploads.
# Without this, every upload fails with "Permission denied" at request time.
chown www-data:www-data /var/www/camagru/uploads

# --- 1. msmtp config -----------------------------------------------------
# Built from .env values; never committed.
MSMTPRC="/etc/msmtprc"

# tls_starttls setting depends on SMTP_SECURE (ssl => off, starttls => on).
case "${SMTP_SECURE:-starttls}" in
    ssl)     STARTTLS="off"  ;;
    starttls) STARTTLS="on"   ;;
    *)        STARTTLS="on"   ;;
esac

cat > "$MSMTPRC" <<EOF
# Generated by entrypoint.sh from environment variables. Do not edit.
defaults
auth on
tls on
tls_starttls ${STARTTLS}
tls_trust_file /etc/ssl/certs/ca-certificates.crt

account default
host ${SMTP_HOST}
port ${SMTP_PORT}
from ${MAIL_FROM}
user ${SMTP_USER}
password ${SMTP_PASS}
EOF

# msmtp must read the config; restrict it to the fpm user.
chown www-data:www-data "$MSMTPRC"
chmod 600 "$MSMTPRC"

# --- 2. Database setup ---------------------------------------------------
# On failure logs through PHP's error log and exits non-zero so the
# container does not serve a broken site.
php /var/www/camagru/bin/setup-db.php

# --- 3. Start php-fpm ----------------------------------------------------
exec php-fpm
