#!/bin/sh
# Camagru php container entrypoint.
# 1. Generate /etc/msmtprc from env vars (phase 1 msmtp driver).
# 2. Run the DB setup (waits for the DB, creates missing tables).
# 3. Exec php-fpm.
#
# Nothing is printed on success: the container console stays quiet.

set -eu

LOG_DIR="/var/log/camagru"
mkdir -p "$LOG_DIR" /var/www/camagru/uploads
# The php-fpm workers run as www-data: they (and msmtp, spawned by mail())
# must be able to write the log files and the uploads. Without this, every
# log write and mail send fails with "Permission denied" at request time.
# Recursive: a file created by any earlier root process (e.g. a debug exec
# into the container) must not block the fpm user either.
chown -R www-data:www-data "$LOG_DIR"
chown www-data:www-data /var/www/camagru/uploads

# --- 1. msmtp config -----------------------------------------------------
# Built from .env values; never committed. Log goes to a file, never stdout.
MSMTPRC="/etc/msmtprc"

# tls_starttls setting depends on SMTP_SECURE (ssl => off, starttls => on).
case "${SMTP_SECURE:-starttls}" in
    ssl)     STARTTLS="off"  ;;
    starttls) STARTTLS="on"   ;;
    *)        STARTTLS="on"   ;;
esac

cat > "$MSMTPRC" <<EOF
# Generated by entrypoint.sh from environment variables. Do not edit.
defaults
auth on
tls on
tls_starttls ${STARTTLS}
tls_trust_file /etc/ssl/certs/ca-certificates.crt
logfile ${LOG_DIR}/msmtp.log
syslog off

account default
host ${SMTP_HOST}
port ${SMTP_PORT}
from ${MAIL_FROM}
user ${SMTP_USER}
password ${SMTP_PASS}
EOF

# msmtp must read the config; restrict it to the fpm user.
chown www-data:www-data "$MSMTPRC" 2>/dev/null || true
chmod 600 "$MSMTPRC"

# --- 2. Database setup ---------------------------------------------------
# Silent on success; on failure logs to file and exits non-zero.
php /var/www/camagru/bin/setup-db.php

# --- 3. Start php-fpm ----------------------------------------------------
exec php-fpm
