<?php
// MsmtpMailer: the mail sender of the application, and the only code allowed
// to call mail(). Builds the MIME message with MessageBuilder and hands it to
// PHP mail(), whose sendmail_path is "/usr/bin/msmtp -t" (see
// docker/php/php.ini). msmtp then relays the message to the SMTP server
// configured in /etc/msmtprc (generated by entrypoint.sh) and writes its own
// log to a file, never the container console.
//
// mail() returns false when the sendmail process fails, which is how the
// caller detects a delivery failure.

declare(strict_types=1);

namespace App\Services\Mail;

use App\Core\Env;

class MsmtpMailer
{
    private string $fromAddress;
    private ?string $fromName;

    public function __construct()
    {
        // Sender identity comes from the environment (.env); never hardcoded.
        $this->fromAddress = Env::require('MAIL_FROM');
        $this->fromName = Env::get('MAIL_FROM_NAME');
    }

    /**
     * Send an email through mail() + msmtp. Returns true on success, false on
     * failure (caller logs and continues).
     */
    public function send(string $to, string $subject, string $htmlBody, ?string $textBody = null): bool
    {
        $to = MessageBuilder::sanitizeHeaderValue($to);
        $subject = MessageBuilder::encodeSubject($subject);

        if ($textBody === null) {
            // Single-part HTML message.
            $headers = MessageBuilder::headers($this->fromAddress, $this->fromName, 'text/html; charset=UTF-8');
            $headers[] = 'Content-Transfer-Encoding: base64';
            $body = MessageBuilder::encodeBody($htmlBody);
        } else {
            // Multipart/alternative: text + HTML with a random boundary.
            $boundary = 'camagru-' . bin2hex(random_bytes(16));
            $headers = MessageBuilder::headers(
                $this->fromAddress,
                $this->fromName,
                'multipart/alternative; boundary="' . $boundary . '"'
            );
            $body = MessageBuilder::body($htmlBody, $textBody, $boundary);
        }

        // mail() adds the To and Subject headers itself and passes the rest
        // through; msmtp -t reads the envelope recipient from the To header.
        // The return value is false when msmtp exits non-zero.
        return mail($to, $subject, $body, implode("\r\n", $headers));
    }
}
